name: SimpleBackupReloaded
main: com.exolius.simplebackup.SimpleBackup
version: ${project.version}
description: Updated version of the original SimpleBackup plugin by Exolius
author: Derkades
authors: [Exolius]

commands:
   sbackup:
      description: Run map backup
      usage: /sbackup

permissions:
   simplebackup.use:
      description: Run map backup
      default: op
